--- Makefile.old	2005-11-04 00:13:07.000000000 -0500
+++ Makefile	2005-11-17 12:45:31.000000000 -0500
@@ -18,6 +18,7 @@
 
 wwinitrd:
 	(cd src/; tar xvzf busybox.tar.gz)
+	patch -p1 < gzip.c.patch
 	cp src/configs/busybox.config src/busybox/.config
 	while true; do echo; done | make -C src/busybox
 	make -C src/busybox install
